### ISSUE TITLE
Small typos

### ISSUE THREAD

**Issue by adolfosilva** [heathermiller/dist-prog-book#19]
Chapter 1:
"able to **communication** information successfully"
"the complexity **of the of this** remote procedure has no upper bound."
"Aggregating multiple Filters is **alos** possible in Finagle."
"is a modified implementation **to of** the RPC paradigm"
"it’s become very difficult differentiate"

Is the RPC example in Python3, supposed to fail? It's being called without arguments.

**Comment by heathermiller** [comment]
Hey @MuzammilAR or @pgrosu, could you quickly have a look at the RPC example that @adolfosilva  mentions? (I will fix the typos)

**Comment by muzammilar** [comment]
Fixed. And tested again. This should be working.
There was an unnecessary argument being passed to the function.

**Comment by heathermiller** [comment]
Thanks Muzammil!

**Comment by natdempk** [comment]
Looks like this was fixed, going to close. Feel free to re-open if not!
