### ISSUE TITLE
Missing Image in Ch. 6

### ISSUE THREAD

**Issue by DrQz** [heathermiller/dist-prog-book#38]
Section 3. **The CAP Theorem**. 
This [image link](https://github.com/heathermiller/dist-prog-book/blob/f27ba2bd06be195a06fe11b571aebd9a7c1ef930/chapter/6/resources/partitioned-network.jpg
), essential to the presentation, gets a 404.

**Comment by natdempk** [comment]
Thanks for pointing this out, this has been fixed. If you go to http://dist-prog-book.com/chapter/6/acidic-to-basic-how-the-database-ph-has-changed.html#3-the-cap-theorem you can see the image now works.

**Comment by DrQz** [comment]
Thank you for the quick action. 👍
